import { useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { useWeeklyReport } from '../../hooks/useAnalytics';

const Section = ({ title, children }) => (
  <div className="mb-6 break-inside-avoid">
    <h2 className="text-black font-semibold text-lg mb-2 print:text-black">{title}</h2>
    <div className="bg-white rounded-xl border border-black/10 p-4 print:border-black/20">
      {children}
    </div>
  </div>
);

export default function AdminWeeklyPrint() {
  const [params] = useSearchParams();
  const communityScope = params.get('communityScope') === 'all-time' ? 'all-time' : 'weekly';
  const scopeLabel = communityScope === 'all-time' ? 'All-time' : 'This week';
  const { data: wr, isLoading, error } = useWeeklyReport({ communityScope });
  const weekly = wr?.data;
  const reportScopeLabel = weekly?.header?.reportScopeLabel || weekly?.iotWaterLevel?.scopeLabel || scopeLabel;
  const alertEmptyText = reportScopeLabel === 'All-time'
    ? 'No alerts recorded for all-time data.'
    : 'No alerts recorded for this week.';

  useEffect(() => {
    if (params.get('auto') === '1' && weekly && !isLoading && !error) {
      setTimeout(() => window.print(), 150);
    }
  }, [params, weekly, isLoading, error]);

  return (
    <div className="max-w-4xl mx-auto bg-gray-50 text-black p-6 print:bg-white">
      <div className="flex items-center justify-between mb-6 print:hidden">
        <h1 className="text-2xl font-black">Weekly Report (Print)</h1>
        <div className="flex gap-2">
          <button onClick={() => window.print()} className="px-3 py-2 rounded-lg border border-black/10 bg-white hover:bg-gray-100 text-sm">Print</button>
          <a href="/admin/weekly" className="px-3 py-2 rounded-lg border border-black/10 bg-white hover:bg-gray-100 text-sm">Back</a>
        </div>
      </div>

      {isLoading && <div>Generating…</div>}
      {error && <div className="text-red-600">Failed to load</div>}

      {!isLoading && !error && weekly && (
        <div className="text-sm">
          <Section title="Header">
            <div className="grid sm:grid-cols-2 gap-2">
              <div>
                <div><strong>System:</strong> {weekly.header?.systemName}</div>
                <div><strong>Community/Barangay:</strong> {weekly.header?.community}</div>
                <div><strong>Date range:</strong> {weekly.header?.dateRange}</div>
                <div><strong>Report scope:</strong> {reportScopeLabel}</div>
              </div>
              <div>
                <div><strong>Generated on:</strong> {new Date(weekly.header?.generatedOn || Date.now()).toLocaleString()}</div>
                <div><strong>Generated by:</strong> {weekly.header?.generatedBy}</div>
                <div><strong>Status:</strong> {weekly.header?.systemStatus}</div>
              </div>
            </div>
          </Section>

          <Section title={`IoT Water Level Summary (${reportScopeLabel})`}>
            <div className="grid grid-cols-2 gap-3 mb-3">
              <div><strong>Average (cm):</strong> {weekly.iotWaterLevel?.overall?.averageCm ?? '—'}</div>
              <div><strong>Max (cm):</strong> {weekly.iotWaterLevel?.overall?.maxCm ?? '—'}</div>
              <div><strong>Min (cm):</strong> {weekly.iotWaterLevel?.overall?.minCm ?? '—'}</div>
              <div><strong>Days above threshold:</strong> {weekly.iotWaterLevel?.overall?.daysAboveThreshold ?? 0}</div>
            </div>
            <div className="text-xs text-black/70"><em>Note:</em> {weekly.iotWaterLevel?.note}</div>
          </Section>

          <Section title={`Community Reports Summary (${reportScopeLabel})`}>
            <div className="grid grid-cols-2 gap-3 mb-3">
              <div><strong>Total Reports:</strong> {weekly.communityReports?.totalReports ?? 0}</div>
              <div><strong>Verified:</strong> {weekly.communityReports?.verified ?? 0}</div>
              <div><strong>Unverified:</strong> {weekly.communityReports?.unverified ?? 0}</div>
              <div><strong>Rejected:</strong> {weekly.communityReports?.rejected ?? 0}</div>
            </div>
            <div className="grid md:grid-cols-2 gap-4">
              <div>
                <div className="font-medium mb-1">By Severity</div>
                <ul className="space-y-1">
                  {[
                    { label: 'Minor Flood', key: 'Minor Flood' },
                    { label: 'Moderate Flood', key: 'Moderate Flood' },
                    { label: 'Severe Flood', key: 'Severe Flood' },
                  ].map(({ label, key }) => (
                    <li key={key} className="flex justify-between">
                      <span>{label}</span>
                      <span>{weekly.communityReports?.bySeverity?.[key] ?? 0}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <div className="font-medium mb-1">Most Reported Areas</div>
                <table className="w-full border border-black/10">
                  <thead>
                    <tr className="text-left">
                      <th className="py-1 px-2 border-b border-black/10">Area</th>
                      <th className="py-1 px-2 border-b border-black/10">Reports</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(weekly.communityReports?.mostReportedAreas || []).map((a) => (
                      <tr key={a.name}>
                        <td className="py-1 px-2 border-b border-black/5">{a.name}</td>
                        <td className="py-1 px-2 border-b border-black/5">{a.count}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                <div className="mt-2 text-xs">
                  <strong>Peak Hours:</strong> {(weekly.communityReports?.peakHours || []).map((h) => `${h.hour}:00`).join(', ') || '—'}
                </div>
              </div>
            </div>
          </Section>

          <Section title={`Alerts and Warnings (${reportScopeLabel})`}>
            <div className="space-y-1">
              {(weekly.alerts || []).length === 0 && <div>{alertEmptyText}</div>}
              {(weekly.alerts || []).map((a, idx) => (
                <div key={idx} className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">{a.alertType}</div>
                    <div className="text-xs text-black/70">{a.message}</div>
                  </div>
                  <div className="text-xs">{new Date(a.timestamp).toLocaleString()}</div>
                </div>
              ))}
            </div>
          </Section>

          <Section title="Offline Data Sync Status">
            <div className="grid grid-cols-2 gap-3">
              <div><strong>Unsynced Records:</strong> {weekly.offlineSync?.unsyncedRecords ?? 'N/A'}</div>
              <div><strong>Last Successful Sync:</strong> {weekly.offlineSync?.lastSuccessfulSync ? new Date(weekly.offlineSync.lastSuccessfulSync).toLocaleString() : 'N/A'}</div>
              <div><strong>Local Cache (bytes):</strong> {weekly.offlineSync?.localCacheBytes ?? 'N/A'}</div>
              <div><strong>Next Scheduled Sync:</strong> {weekly.offlineSync?.nextScheduledAttempt ? new Date(weekly.offlineSync.nextScheduledAttempt).toLocaleString() : 'N/A'}</div>
            </div>
            <div className="text-xs text-black/70 mt-2"><em>Note:</em> {weekly.offlineSync?.note}</div>
          </Section>

          <Section title={`Insights (${reportScopeLabel})`}>
            <div>{weekly.insights?.summaryText}</div>
            <div className="mt-2 text-xs flex gap-3">
              {weekly.insights?.waterLevelChangePct != null && (
                <span>Water level change: {weekly.insights.waterLevelChangePct?.toFixed ? weekly.insights.waterLevelChangePct.toFixed(1) : weekly.insights.waterLevelChangePct}%</span>
              )}
              {weekly.insights?.engagementChangePct != null && (
                <span>Community engagement change: {weekly.insights.engagementChangePct?.toFixed ? weekly.insights.engagementChangePct.toFixed(1) : weekly.insights.engagementChangePct}%</span>
              )}
            </div>
          </Section>

          <div className="text-xs text-black/70">
            <div>{weekly.footer?.copyright}</div>
            <div>{weekly.footer?.developedBy}</div>
            <div>{weekly.footer?.generator}</div>
          </div>
        </div>
      )}
    </div>
  );
}
